import { memo } from "react";

/**
 * Equivalent Tailwind gradient classes:
 * bg-gradient-to-bl from-[#d88449] to-[#d84b5d]
 */

interface GeminiFillPixelProps {
  size?: number;
  className?: string;
}

export const GeminiFillPixel = memo(function GeminiFillPixel({
  size = 156,
  className,
}: GeminiFillPixelProps) {
  return (
    <svg
      className={className}
      height={size}
      shapeRendering="crispEdges"
      viewBox="0 0 156 156"
      width={size}
    >
      <title>Gemini</title>
      <defs>
        <linearGradient
          gradientUnits="userSpaceOnUse"
          id="GeminiFillPixelGradient"
          x1="156"
          x2="0"
          y1="0"
          y2="156"
        >
          <stop offset="0%" stopColor="#d88449" />
          <stop offset="100%" stopColor="#d84b5d" />
        </linearGradient>
      </defs>
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={6}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={12}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={18}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={24}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={24}
        x={66}
        y={30}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={24}
        x={66}
        y={36}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={36}
        x={60}
        y={42}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={48}
        x={54}
        y={48}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={60}
        x={48}
        y={54}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={72}
        x={42}
        y={60}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={96}
        x={30}
        y={66}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={144}
        x={6}
        y={72}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={144}
        x={6}
        y={78}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={96}
        x={30}
        y={84}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={72}
        x={42}
        y={90}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={60}
        x={48}
        y={96}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={48}
        x={54}
        y={102}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={36}
        x={60}
        y={108}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={24}
        x={66}
        y={114}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={24}
        x={66}
        y={120}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={126}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={132}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={138}
      />
      <rect
        fill="url(#GeminiFillPixelGradient)"
        height={6}
        width={12}
        x={72}
        y={144}
      />
    </svg>
  );
});
