import { memo } from "react";

/**
 * Equivalent Tailwind gradient classes:
 * bg-gradient-to-bl from-[#d8844a] to-[#d74b5e]
 */

interface NiriPixelProps {
  size?: number;
  className?: string;
}

export const NiriPixel = memo(function NiriPixel({
  size = 156,
  className,
}: NiriPixelProps) {
  return (
    <svg
      aria-label="Niri"
      className={className}
      height={size}
      role="img"
      shapeRendering="crispEdges"
      viewBox="0 0 156 156"
      width={size}
    >
      <defs>
        <linearGradient
          gradientUnits="userSpaceOnUse"
          id="NiriPixelGradient"
          x1="156"
          x2="0"
          y1="0"
          y2="156"
        >
          <stop offset="0%" stopColor="#d8844a" />
          <stop offset="100%" stopColor="#d74b5e" />
        </linearGradient>
      </defs>
      <rect fill="url(#NiriPixelGradient)" height={6} width={24} x={42} y={0} />
      <rect fill="url(#NiriPixelGradient)" height={6} width={36} x={36} y={6} />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={48}
        x={36}
        y={12}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={54}
        x={36}
        y={18}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={60}
        x={36}
        y={24}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={66}
        x={36}
        y={30}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={72}
        x={36}
        y={36}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={72}
        x={36}
        y={42}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={78}
        x={36}
        y={48}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={30}
        x={36}
        y={54}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={42}
        x={72}
        y={54}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={30}
        x={36}
        y={60}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={36}
        x={84}
        y={60}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={36}
        y={66}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={30}
        x={90}
        y={66}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={36}
        y={72}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={96}
        y={72}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={36}
        y={78}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={96}
        y={78}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={36}
        y={84}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={96}
        y={84}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={36}
        y={90}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={96}
        y={90}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={18}
        x={42}
        y={96}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={18}
        x={96}
        y={96}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={24}
        x={42}
        y={102}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={18}
        x={90}
        y={102}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={18}
        x={48}
        y={108}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={12}
        x={90}
        y={108}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={48}
        x={54}
        y={126}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={60}
        x={48}
        y={132}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={60}
        x={48}
        y={138}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={60}
        x={48}
        y={144}
      />
      <rect
        fill="url(#NiriPixelGradient)"
        height={6}
        width={48}
        x={54}
        y={150}
      />
    </svg>
  );
});
